using System.Collections.Generic;

namespace Titan.NF.Client.Browsers
{
    internal class BrowsersRegistry
    {
        public static List<string> IgnoreableBase64 = new List<string>()
        {
            "Y2FjaGU=",
            "V2luZG93cw==",
            "UHJvZ3JhbURhdGE=",
            "UHJvZ3JhbSBGaWxlcw==",
            "JFJFQ1lDTEUuQklO",
            "Q2xpY2tUb1J1bg==",
            "RGV2aWNlIFN0YWdl",
            "VmlzdWFsU3R1ZGlv",
            "UGFja2FnZSBDYWNoZQ==",
            "Q2FjaGU=",
            "JFJlY3ljbGUuQmlu",
            "JFN5c1Jlc2V0",
            "UmVjb3Zlcnk=",
            "QS1Wb2x1dGU=",
            "SW50ZWw=",
            "Q0VG",
            "Q29tbXM=",
            "RDNEU0NhY2hl",
            "UGFja2FnZXM=",
            "TWljcm9zb2Z0LldpbmRvd3M=",
            "VGVtcA==",
            "V2luZG93cyBEZWZlbmRlcg==",
            "dmNwa2c=",
            "T2ZmaWNl",
            "T25lRHJpdmU=",
            "bWluZ3c2NA==",
            "TGli",
            "JFdpblJFQWdlbnQ=",
            "bXN5czY0",
            "UGVyZkxvZ3M=",
            "RG9jdW1lbnRzIGFuZCBTZXR0aW5ncw==",
            "bGx2bQ==",
            "Y2hvY29sYXRleQ==",
            "UGhwc3Rvcm1Qcm9qZWN0cw==",
            "bm9kZV9tb2R1bGVz",
            "SmV0QnJhaW5z",
            "ZGlzY29yZF9hcGk=",
        };

        public static List<string> SearcheableBase64 = new List<string>()
        {
            "MzYwQnJvd3Nlcg==",
            "MzYwc2U2",
            "N1N0YXI=",
            "QVZBU1QgU29mdHdhcmU=",
            "QVZH",
            "QWNXZWJCcm93c2Vy",
            "QmFpZHUgU3Bhcms=",
            "Qmxpc2s=",
            "QmxhY2tIYXdr",
            "QnJhdmU=",
            "QnJvbWl1bQ==",
            "Q0NsZWFuZXJCcm93c2Vy",
            "Q2F0YWxpbmFHcm91cA==",
            "Q2VudEJyb3dzZXI=",
            "Q2hlZG90",
            "Q2hyb21l",
            "Q2hyb21vZG8=",
            "Q29jQ29j",
            "Q29tb2Rv",
            "Q29vbE5vdm8=",
            "Q29vd29u",
            "Q3J5cHRvVGFiIEJyb3dzZXI=",
            "RWxlbWVudHMgQnJvd3Nlcg==",
            "RXBpYyBCcm93c2Vy",
            "RmVucmlyIEluYw==",
            "RmxvY2s=",
            "R2FyZW5hUGx1cw==",
            "R2hvc3RCcm93c2Vy",
            "Q2hyb21lIFN4Uw==",
            "SW5zb21uaWFjQnJvd3Nlcg==",
            "SXJpZGl1bQ==",
            "Sy1NZWxvbg==",
            "S2luemE=",
            "TGVub3Zv",
            "TGllYmFv",
            "Q2hyb21lUGx1cw==",
            "TWF4dGhvbg==",
            "TWF4dGhvbjM=",
            "TWF4dGhvbjU=",
            "RWRnZQ==",
            "TmV0Ym94QnJvd3Nlcg==",
            "TmljaHJvbWU=",
            "T3BlcmEgQ3J5cHRvIERldmVsb3Blcg==",
            "UmFmb3RlY2g=",
            "T3BlcmEgTmVvbg==",
            "T3BlcmEgU3RhYmxl",
            "UUlQIFN1cmY=",
            "Um9ja01lbHQ=",
            "U1JXYXJlSXJvbg==",
            "U2FmZXIgVGVjaG5vbG9naWVz",
            "U2FsYW1XZWI=",
            "U2lkZWtpY2s=",
            "U2xlaXBuaXI=",
            "U3B1dG5paw==",
            "U3VoYmE=",
            "U3VwZXJiaXJk",
            "U3dpbmdCcm93c2Vy",
            "VGVuY2VudA==",
            "VG9yQnJv",
            "VG9yY2g=",
            "VHdpbmtzdGFy",
            "VUNCcm93c2Vy",
            "VVJCcm93c2Vy",
            "VmlhU2F0",
            "Vml2YWxkaQ==",
            "WHBvbQ==",
            "WHZhc3Q=",
            "WWFuZGV4",
            "dUNvek1lZGk=",
            "VGl0YW4gQnJvd3Nlcg=="
        };

        public static Dictionary<string, string> ExtensionsMap = new Dictionary<string, string>()
        {
            ["TWV0YW1hc2s="] = "nkbihfbeogaeaoehlefnkodbefgpgknn",
            ["QmluYW5jZUNoYWlu"] = "fhbohimaelbohpjbbldcngcnapndodjp",
            ["Qml0YXBw"] = "fihkakfobkmkjojpchpfgcmhfjnmnfpi",
            ["Q29pbjk4"] = "aeachknmefphepccionboohckonoeemg",
            ["REFwcFBsYXk="] = "lodccjjbdhfakaekdiahmedfbieldgik",
            ["RXF1YWw="] = "blnieiiffboillknjnepogjhkgnoapac",
            ["R3VpbGQ="] = "nanjmdknhkinifnkgdcggcfnhdaammmj",
            ["SUNPTmV4"] = "flpiciilemghbmfalicajoolhkkenfel",
            ["TWF0aA=="] = "afbcbjpbpfadlkmhmclhkeeodmamcflc",
            ["TW9ib3g="] = "fcckkdbjnoikooededlapcalpionmalo",
            ["UGhhbnRvbQ=="] = "bfnaelmomeimhlpmgjnjophhpkkoljpa",
            ["VHJvbkxpbms="] = "ibnejdfjmmkpcnlpebklmnkoeoihofec",
            ["WGluUGF5"] = "bocpokimicclpaiekenaeelehdjllofo",
            ["VG9u"] = "nphplpgoakhhjchkkhmiggakijnkhfnd",
            ["U29sbGV0"] = "fhmfendgdocmcbmfikdcogofphimnkno",
            ["U2xvcGU="] = "pocmplpaccanhmnllbbkpgfliimjljgo",
            ["U3RhcmNvaW4="] = "mfhbebgoclkghebffdldpobeajmbecfk",
            ["SGlyb1dhbGxldA=="] = "ldinpeekobnhjjdofggfgjlcehhmanlj",
            ["TWV0YVdhbGxldA=="] = "bkklifkecemccedpkhcebagjpehhabfb",
            ["U3dhc2g="] = "cmndjbecilbocjfkibfbifhngkdmjgog",
            ["Rmlubmll"] = "cjmkndjhnagcfbpiemnkdpomccnjblmj",
            ["S2VwbHI="] = "dmkamcknogkgcdfhhbddcghachkejeap",
            ["Q3JvY29iaXQ="] = "pnlfjmlcjdjgkddecgincndfgegkecke",
            ["T3h5Z2Vu"] = "fhilaheimglignddkjgofkcbgekhenbh",
            ["TmlmdHk="] = "jbdaocneiiinmjbjlgalhcelgbejmnid",
            ["TGlxdWFsaXR5"] = "kpfopkelmapcoipemfendmdcghnegimn",
            ["Um9uaW4="] = "fnjhmkhhmkbjkkabndcnnogagogbneec",
            ["T2FzaXM="] = "ppdadbejkmjnefldpcdjhnkpbjkikoip",
            ["VGVtcGxl"] = "ookjlbkiijinhpmnjffcofjonbfbgaoc",
            ["UG9udGVt"] = "phkbamefinggmakgklpkljjmgibohnba",
            ["U29sZmxhcmU="] = "bhhhlbepdkbapadjdnnojkbgioiodbic",
            ["WW9yb2k="] = "ffnbelfdoeiohenkjibnmadjiehjhajb",
            ["aVdhbGxldA=="] = "kncchdigobghenbbaddojjnnaogfppfj",
            ["V29tYmF0"] = "amkmjjmmflddogmhpjloimipbofnfjih",
            ["Q29pbmJhc2U="] = "hnfanknocfeofbddgcijnmhnfnkdnaad",
            ["TWV3Q3g="] = "nlbmnnijcnlegkjjpcfjclmcfggfefdm",
            ["SmF4eExpYmVydHkod2ViKQ=="] = "cjelfplplebdjjenllpjcblmjkfcffne",
            ["T25lS2V5"] = "jnmbobjmhlngoefaiojfljckilhhlhcj",
            ["SHljb25MaXRlQ2xpZW50"] = "bcopgchhojmggmffilplmbdicgaihlkp",
            ["U3ViV2FsbGV0KFBvbGthZG90KQ=="] = "onhogfjeacnfoofkfgppdlbmlmnplgbn",
            ["R29ieQ=="] = "jnkelfanjkeadonecabehalmbgpfodjm",
            ["VGV6Qm94"] = "mnfifefkajgofkcjkemidiaecocnkjeh",
            ["T05UT1dhbGxldA=="] = "ifckdpamphokdglkkdomedpdegcjhjdp",
            ["SGFzaHBhY2s="] = "gjagmgiddbbciopjhllkdnddhcglnemk",
            ["Q3lhbm8="] = "dkdedlpgdmmkkfjabffeganieamfklkm",
            ["U2VuZGVyV2FsbGV0"] = "epapihdplajcdnnkdeiahlgigofloibg",
            ["WmVjcmV5"] = "ojbpcbinjmochkhelkflddfnmcceomdi",
            ["QXVybw=="] = "cnmamaachppnkjgnildpdmkaakejnhae",
            ["VGVycmFTdGF0aW9u"] = "aiifbnbfobpmeekipheeijimdpnlpgpp",
            ["S2FyZGlhQ2hhaW4="] = "pdadjkfkgcafgbceimcpbkalnfnepbnk",
            ["UmFiYnk="] = "acmacodkjbdgmoleebolmdjonilkdbch",
            ["TmVvTGluZQ=="] = "cphhlgmgameodnhkjdmkpanlelnlohao",
            ["TmFib3g="] = "nknhiehlklippafakaeklbeglecifhad",
            ["WERlRmk="] = "hmeobnfnfcmdkdcmlblgagmfpfboieaf",
            ["S0hD"] = "hcflpincpppdclinealmandijcmnkbgn",
            ["T25lS2V5"] = "jnmbobjmhlngoefaiojfljckilhhlhcj",
            ["QXVybw=="] = "cnmamaachppnkjgnildpdmkaakejnhae",
            ["Q0xX"] = "nhnkbkgjikgcigadomkphalanndcapjk",
            ["UG9seW1lc2g="] = "jojhfeoedkpkglbfimdfabpdfjaoolaf",
            ["WmlsUGF5"] = "klnaejjgbibmhlephnhpmaofohgkpgkd",
            ["QnlvbmU="] = "nlgbhdfgdhgbiamfdfmbikcdghidoadd",
            ["RXRlcm5s"] = "kmhcihpebfmpgmihbkipmjlmmioameka",
            ["TmFtaQ=="] = "lpfcbjknijpeeillifnkikgncikgfhdo",
            ["TWFpYXJEZUZpV2FsbGV0"] = "dngmlblcodfobpdpecaadgfbcggfjfnm",
            ["TGVhZldhbGxldA=="] = "cihmoadaighcejopammfbmddcmdekcje",
            ["VHJ1c3RXYWxsZXQ="] = "egjidjbpglichdcondbcbdnbeeppgdph",
            ["RXhvZHVzKHdlYik="] = "aholpfdialjgjfhomihkjbmgjidlcdno",
            ["QnJhdmVXYWxsZXQ="] = "odbfpeeihdkbihmopkbjmoonfanlbfcl",
            ["TUVXQ1g="] = "nlbmnnijcnlegkjjpcfjclmcfggfefdm",
            ["WERDUGF5"] = "bocpokimicclpaiekenaeelehdjllofo",
            ["RmxpbnQ="] = "hnhobjmcibchnmglfbldbfabcgaknlkj",
            ["Q2FyZFdhbGxldA=="] = "apnehcjmnengpnmccpaibjmhhoadaico",
            ["QmluYW5jZUNoYWluV2FsbGV0"] = "fhbohimaelbohpjbbldcngcnapndodjp",
            ["Q3J5cHRvQWlyZHJvcA=="] = "dhgnlgphgchebgoemcjekedjjbifijid",
            ["TUVXIA==CX"] = "nlbmnnijcnlegkjjpcfjclmcfggfefdm",
            ["REFwcFBsYXk="] = "lodccjjbdhfakaekdiahmedfbieldgik",
            ["QXV0aGVudGljYXRvcg=="] = "bhghoamapcdpbohphigoooaddinpkbai",
            ["QXV0aHk="] = "gaedmjdfmmahhbjefcbgaolhhanlaolb",
            ["RU9TQXV0aGVudGljYXRvcg=="] = "oeljdldpnmdbchonielidgobddffflal",
            ["R0F1dGhBdXRoZW50aWNhdG9y"] = "ilgcnhelpchnceeipipijaljkblbcobl"
        };
    }
}
